django/project/example_cms_app/urls.py
from django.conf.urls.defaults import *
from django.views.decorators.csrf import csrf_exempt
from django.views.generic import DetailView

from haystack.forms import ModelSearchForm
from haystack.query import SearchQuerySet
from haystack.views import SearchView, search_view_factory

from models import AnotherExampleModel
from forms import ExampleSearchForm
from views import ExampleSearchView

sqs = SearchQuerySet().models(AnotherExampleModel)

urlpatterns = patterns('',
    url(r'^$', csrf_exempt(search_view_factory(
        view_class=ExampleSearchView,
        template='sr_search.html',
        searchqueryset=sqs,
        form_class=ExampleSearchForm,
        results_per_page=15
        )), name='sr_search'),

    url(r'details/(?P<pk>\w+)/$',
        DetailView.as_view(template_name='sr_details.html', model=AnotherExampleModel),
        name='sr_details'),
)

django/project/urls.py
from django.conf.urls.defaults import patterns, include, url
from django.conf import settings

# Uncomment the next two lines to enable the admin:
from django.contrib import admin
admin.autodiscover()

urlpatterns = patterns('',
    # Examples:
    # url(r'^$', 'example_app.views.home', name='home'),
    # url(r'^example/', include('example_app.foo.urls')),

    # Uncomment the admin/doc line below to enable admin documentation:
    # url(r'^admin/doc/', include('django.contrib.admindocs.urls')),

    # Uncomment the next line to enable the admin:
    url(r'^admin/', include(admin.site.urls)),
    #(r'^sr/', include('example_app.urls')),
    url(r'^', include('cms.urls')),
)

if settings.DEBUG:
    urlpatterns = patterns('',
    url(r'^media/(?P<path>.*)$', 'django.views.static.serve',
        {'document_root': settings.MEDIA_ROOT, 'show_indexes': True}),
    url(r'', include('django.contrib.staticfiles.urls')),
) + urlpatterns

django/project/example_cms_app/models.py
from django.db import models
from django.template.defaultfilters import slugify

class ExampleModel(models.Model):
    name = models.CharField(max_length=50)

class AnotherExampleModel(models.Model):
    title = models.CharField(max_length=500)
    slug = models.SlugField(max_length=128, unique=True)
    author = models.CharField(max_length=500)
    region = models.ManyToManyField(ExampleModel)
    # status = models.ForeignKey(ExampleModel, null=True, blank=True)
    long_field = models.TextField()
    published = models.BooleanField(default=False)
    published_date = models.DateField(null=True, blank=True)
    image = models.ImageField(upload_to='sr_imgs')

    def save(self, *args, **kwargs):
        if not self.slug:
            self.slug = slugify(self.title[:128])
            existing = AnotherExampleModel.objects.filter(slug=self.slug).count()
            if existing:
                self.slug = "%s-%d" % (self.slug, existing+1)
        super(AnotherExampleModel, self).save(*args, **kwargs)

    @models.permalink
    def get_absolute_url(self):
        return ('sr_details', (), { 'pk': self.pk })

    def get_abbr(self):
        return "sr"

django/project/lib/models.py
from django.db import models

# Create your models here.

django/project/example_cms_app/forms.py
from django import forms

from models import ExampleModel
from haystack.forms import SearchForm
    
def get_choices(model, field):
    return [ ("", "all...") ] + [ (getattr(x, field), getattr(x, field)) for x in model.objects.all() ]

class ExampleSearchForm(SearchForm):
    q = forms.CharField(max_length=128, required=False, widget=forms.TextInput(attrs={'class': 'search_input'}))
    title = forms.CharField(max_length=500, required=False)
    author = forms.CharField(max_length=500, required=False)
    region = forms.CharField(max_length=255, required=False, widget=forms.Select(choices=get_choices(ExampleModel, 'name')))

    def search(self):
        # First, store the SearchQuerySet received from other processing.
        sqs = super(ExampleSearchForm, self).search()

        if hasattr(self, 'cleaned_data'):
            if not self.cleaned_data.get('q'): # Haystack gives up if no keywords, we don't
                sqs = self.searchqueryset
            if self.cleaned_data['title']:
                sqs = sqs.filter(title__in=[self.cleaned_data['title']])
            if self.cleaned_data['author']:
                sqs = sqs.filter(author__in=[self.cleaned_data['author']])
            if self.cleaned_data['region']:
                sqs = sqs.filter(region=self.cleaned_data['region'])

        return sqs

django/project/example_cms_app/views.py
from lib.views import BaseSearchView

class ExampleSearchView(BaseSearchView):
    data_type = "example"
    type_description = "Example CMS App Data"

django/project/lib/views.py
import urllib

from haystack.views import SearchView

class BaseSearchView(SearchView):
    def get_query(self):
        '''
        Returns query keywords provided by user and empty string if query
        is invalid.

        It also sets query_str to url encoded string of search values so it
        can be used for pagination (or empty string for invalid query).
        '''
        self.query_str = ""
        self.searched = False
        if self.form.is_valid():
            self.searched = True
            query_values = [ (key, value) for key, value in self.form.cleaned_data.items() if value or key == 'q' ]
            self.query_str = urllib.urlencode(query_values)
            return self.form.cleaned_data['q']
        return ''

    def get_results(self):
        '''
        Fetches the results via the form or returns an empty list if there's
        no query to search with.

        Valid queries have at least one form field in its request.
        '''
        query_keys = set(self.request.GET.keys())
        if self.form.is_valid():
            form_keys = set(self.form.cleaned_data.keys())
            if not form_keys.intersection(query_keys):
                self.searched = False
                return []
        return self.form.search()

    def extra_context(self):
        '''
        Adds extra context variables for search page.
        '''
        return {
            'query_string': self.query_str,
            'searched': self.searched
        }

django/project/blog/templates/cmsplugin_blog/cmsplugin_blog_base.html
{% extends "col_1_2.html" %}

{% block "main" %}
    {% block left-col %}{% endblock %}
    {% block right-col %}{% endblock %}
{% endblock %}

django/project/example_cms_app/templates/sr_details.html
{% extends 'col_1_2.html' %}
{% load i18n %}
{% load cms_tags sekizai_tags %}
{% block "sidebar" %}
	<section class="search">
		<form><input class="button" type="button" VALUE="Back to results" onClick="history.go(-1);return true;"></form> 
	</section>
{% endblock %}
{% block "main" %}
<table>
    <tbody>
        <tr>
            <td>Title</td>
            <td><h2 style="border:none;">{{ object.title }}</h2></td>
        </tr>
        <tr>
            <td>Authors</td>
            <td>{{ object.author }}</td>
        </tr>
        <tr>
            <td>Sector and subsector</td>
            <td>{% for sector in object.sector.all %}{{ sector.name }}
                {% if not forloop.last %},{% endif %}{% empty %} None specified{% endfor %}
            </td>
        </tr>
        <tr>
            <td>Regions</td>
            <td>{% for region in object.region.all %}{{ region.name }}
                {% if not forloop.last %},{% endif %}{% empty %} None specified{% endfor %}
            </td>
        </tr>
        <tr>
            <td>Equity Focus</td>
            <td>{% for ef in object.equity_focus.all %}{{ ef.name }}
                {% if not forloop.last %},{% endif %}{% empty %} None specified{% endfor %}
            </td>
        </tr>
        <tr>
            <td>Status</td>
            <td>{{ object.status.status }}</td>
        </tr>
        <tr>
            <td>Review Type</td>
            <td>{{ object.review_type.type }}</td>
        </tr>
        <tr>
            <td>Background</td>
            <td>{{ object.background|safe|linebreaks }}</td>
        </tr>
        <tr>
            <td>Objectives</td>
            <td>{{ object.objectives|safe|linebreaks }}</td>
        </tr>
        <tr>
            <td>Main findings</td>
            <td>{{ object.findings|safe|linebreaks }}</td>
        </tr>
        <tr>
            <td>Methodology</td>
            <td>{{ object.methodology|safe|linebreaks }}</td>
        </tr>
        <tr>
            <td>Quality Assessment</td>
            <td>{{ object.quality_assessment|safe|linebreaks }}</td>
        </tr>
        <tr>
            <td>Publication Source</td>
            <td>{{ object.publication_source|safe|linebreaks }}</td>
        </tr>
        <tr>
            <td>Downloadable link</td>
            <td><a href="{{ object.downloadable_link }}">{{ object.downloadable_link }}</a></td>
        </tr>
    </tbody>
</table>
{% endblock %}

django/project/example_cms_app/templates/sr_search.html
{% extends 'search.html' %}
{% load cms_tags sekizai_tags %}
{% load menu_tags %}

{% block "sidebar" %}
	<nav class="nav_sidebar">
		{% with root=request.current_page.get_root %}
		<h2><a href="{% page_url root %}">{% page_attribute "page_title" root %}</a></h2>
		<ul>
			{% show_menu_below_id root.reverse_id 0 100 100 100 %}
		</ul>{% endwith %}
	</nav>

    <section class="search">
    	<h2>Search <span>systematic reviews</span></h2>
	    <form method="get" action="." class="search_advanced">
	        <fieldset>
	                {{ form.q }}
	                <input type="submit" value="Search" class="search_btn" />
	        </fieldset>
	        <fieldset>
	                <h3>Refine search</h3>
	                <ol>
	                        <li>
	                                <label for="id_title">{{ form.title.label }}</label>
	                                {{ form.title }}
	                        </li>
	                        <li>
	                                <label for="id_author">{{ form.author.label }}</label>
	                                {{ form.author }}
	                        </li>
	                        <li>
	                                <label for="id_sector">{{ form.sector.label }}</label>
	                                {{ form.sector }}
	                        </li>
	                        <li>
	                                <label for="id_subsector">{{ form.subsector.label }}</label>
	                                {{ form.subsector }}
	                        </li>
	                        <li>
	                                <label for="id_region">{{ form.region.label }}</label>
	                                {{ form.region }}
	                        </li>
	                        <li>
	                                <label for="id_equity_focus">{{ form.equity_focus.label }}</label>
	                                {{ form.equity_focus }}
	                        </li>
	                        <li>
	                                <label for="id_status">{{ form.status.label }}</label>
	                                {{ form.status }}
	                        </li>
	                        <li>
	                                <label for="id_type">{{ form.type.label }}</label>
	                                {{ form.type }}
	                        </li>
	                        <li class="toright">
	                                <a href="{% url sr_search %}">Clear search</a>
	                                <input type="submit" value="Search" class="search_btn bottom">
	                        </li>
	                </ol>
	        </fieldset>
	    </form>
    </section>
{% endblock %}

django/project/templates/base.html
{% load i18n %}
{% load cms_tags sekizai_tags %}
{% load menu_tags %}
<!DOCTYPE html>
<html lang="en">
	<head>
		<title>{{ request.current_page.get_title }}</title>
		<meta charset="utf-8" />
		<link rel="stylesheet" href="{{ STATIC_URL }}css/style.css" />
		{% render_block "css" %}
		{% render_block "js" %}
	</head>
	<body class="{{ request.current_page.get_root.get_slug }}">
		{% cms_toolbar %}
		<header class="header_site">
			<nav class="nav_site">
				<ul>
					<li><a href="/">Home</a></li>
					<li><a href="/item1">Item One</a></li>
					<li><a href="/item2">Item Two</a>
					<!-- <li><a href="/events">Events</a></li> -->
					<li class="end"><a href="/contact">Contact us</a></li>
				</ul>
			</nav>
			<hgroup>
				<h1><a href="/"><img src="{{ STATIC_URL }}images/logo.png" alt="Your Logo Here" width="200" height="80"></a></h1>
				<h2>Another fine website by Aptivate</h2>
			</hgroup>
			<nav class="nav_sec">
				<ul>
					<li class="item1"><a href="/item1">open<span>Item One</span></a></li>
					<li class="item2"><a href="/item2">open<span>Item Two</span></a></li>
					<li class="about end"><a href="/about">learn<span>About This Org</span></a></li>
				</ul>
			</nav>
		</header>
		{% block "content" %}
		{% placeholder "main" %}
		{% endblock %}
		<footer>
			<div class="site_info">Copyright &copy; 2012 Aptivate. All rights reserved.</div>
		</footer>
		<script type="text/javascript" src="https://ajax.googleapis.com/ajax/libs/jquery/1.7.1/jquery.min.js"></script>
		<script type="text/javascript" src="{{ STATIC_URL }}js/functions.js"></script>
	</body>
</html>

django/project/templates/col_1_2.html
{% extends "base.html" %}
{% load i18n %}
{% load cms_tags sekizai_tags %}
{% load menu_tags %}
{% block "content" %}
		<div class="content_wrap">
			<div class="content">
				<article role="main" class="article_page">
					<div class="page">
						<header class="header_page">
							<h1>{% page_attribute "page_title" %}</h1>
						</header>
					<!-- Main content start -->
						{% block "main" %}
						<div class="featured_image">
							{% placeholder "featured_image" %}
						</div>
						{% placeholder "main" %}
						{% endblock %}
						<!-- Main content end -->
					</div>	
				</article>
				<aside class="aside_site">
					<!-- Sidebar start -->
					{% block "sidebar" %}
					<nav class="nav_sidebar">
						{% with root=request.current_page.get_root %}
						<h2><a href="{% page_url root %}">{% page_attribute "page_title" root %}</a></h2>
						<ul>
							{% show_menu_below_id root.reverse_id 0 100 100 100 %}
						</ul>{% endwith %}
					</nav>
					{% placeholder "sidebar" %}
					{% endblock %}
					<!-- Sidebar end -->
				</aside>
			</div>
		</div>
{% endblock %}

django/project/templates/homepage.html
{% extends "base.html" %}
{% load i18n %}
{% load cms_tags sekizai_tags %}
{% load menu_tags %}
{% block "content" %}
		<div class="content_wrap">
			<div class="content home">
				<article role="main" class="article_page">
					<div class="page">
						<header class="header_page">
							<h1>{% page_attribute "page_title" %}</h1>
						</header>
					<!-- Main content start -->
						{% block "main" %}{% placeholder "main" %}{% endblock %}
						<!-- Main content end -->
					</div>	
				</article>
				<aside class="aside_site">
					<!-- Sidebar start -->
					{% block "sidebar" %}{% placeholder "sidebar" %}{% endblock %}
					<!-- Sidebar end -->
				</aside>
			</div>
		</div>
{% endblock %}

django/project/templates/page_2col.html
{% extends "base.html" %}
{% load i18n %}
{% load cms_tags sekizai_tags %}
{% load menu_tags %}
{% block "content" %}
		<div class="content_wrap">
			<div class="content page">
				<article role="main" class="article_page">
					<div class="page">
						<header class="header_page">
							<h1>{% page_attribute "page_title" %}</h1>
						</header>
					<!-- Main content start -->
						{% block "main" %}
						{% placeholder "main" %}{% endblock %}
						<!-- Main content end -->
					</div>	
				</article>
				<aside class="aside_site">
					<!-- Sidebar start -->
					{% block "sidebar" %}
					<nav class="nav_sidebar">
						<ul>
							{% show_menu_below_id "about" 0 100 100 100 %}
						</ul>
					</nav>
					{% placeholder "sidebar" %}
					{% endblock %}
					<!-- Sidebar end -->
				</aside>
			</div>
		</div>
{% endblock %}

django/project/templates/search.html
{% extends 'col_1_2.html' %}
{% load i18n %}
{% load cms_tags sekizai_tags %}
{% block "main" %}

        {% if searched %}
    <div class="search_results">
            <h2>Search results for: <span>{{ query|default:"all" }}</span></h2>

            {% if page.object_list %}
            <nav>
                    <div class="sort_by">
                        <span>sort by:</span>
                        <select name="sort_by">
                                <option value="date">Publication date</option>
                                <option value="type">Publication type</option>
                        </select>
                    </div>
                    <div class="pager">
                            <span>show {{ page.start_index }}-{{ page.end_index }} of <strong>{{ page.paginator.count }}</strong></span>
                            <a href="#" class="view_all">view all</a>
                    </div>
                    {% if page.has_previous or page.has_next %}<div class="next_prev">
                        {% if page.has_previous %}<a href="?{{ query_string }}&amp;page={{ page.previous_page_number }}">{% endif %}&laquo; Previous{% if page.has_previous %}</a>{% endif %}
                        |
                        {% if page.has_next %}<a href="?{{ query_string }}&amp;page={{ page.next_page_number }}">{% endif %}Next &raquo;{% if page.has_next %}</a>{% endif %}
                    </div>{% endif %}
            </nav>

            <ol>{% for result in page.object_list %}
                <li>
                    <article data-type="{{ result.app_label }}">
                        <div class="meta">
                            <abbr title="{{ result.verbose_name }}" class="{{ result.object.get_abbr|lower }}_icon">{{ result.object.get_abbr }}</abbr>{% if result.object.funded_3ie %}
                            <abbr title="3ie funded" class="funded_icon">3ie</abbr>
                            {% endif %}<br />
                            <strong>{% if result.object.published_date %}<time datetime="{{ result.object.published_date|date:"Y-01" }}">{{ result.object.published_date|date:"Y" }}</time>{% else %}?{% endif %}</strong><br />
                            {{ result.object.status.status }}
                        </div>
                        <div class="article">
                                <div>
                                        <h2><a href="{{ result.object.get_absolute_url }}">{{ result.object.title }}</a></h2>
                                        <p class="findings">
                                            {{ result.object.findings|safe|truncatewords:20 }}
                                        </p>
                                        <footer>
                                                <span class="sector"><strong>sector:</strong> {% for r in result.sector %}{{ r }}{% if not forloop.last %}, {% endif %}{% empty %}No region{% endfor %}</span>{% comment %}TODO:Investigate why join filter fails on this field for SR{% endcomment %}<br />
                                                <span class="region"><strong>regions:</strong> {% for r in result.region %}{{ r }}{% if not forloop.last %}, {% endif %}{% empty %}No region{% endfor %}</span>{% comment %}TODO:Investigate why join filter fails on this field for SR{% endcomment %}
                                        </footer>
                                </div>
                        </div>
                    </article>
                </li>
            {% endfor %}</ol>
            {% else %}<p>No results found.</p>{% endif %}

            {% if page.has_previous or page.has_next %}
                <div class="next_prev">
                    {% if page.has_previous %}<a href="?{{ query_string }}&amp;page={{ page.previous_page_number }}">{% endif %}&laquo; Previous{% if page.has_previous %}</a>{% endif %}
                    |
                    {% if page.has_next %}<a href="?{{ query_string }}&amp;page={{ page.next_page_number }}">{% endif %}Next &raquo;{% if page.has_next %}</a>{% endif %}
                </div>
            {% endif %}
    </div>
        {% else %}
{% block "before_search" %}
            {% placeholder "main" %}    
{% endblock %}
        {% endif %}
{% endblock %}